apiVersion: apps/v1
kind: Deployment
metadata:
  name: availabilityapp
  labels:
    app: availability
spec:
  replicas: 2
  selector:
    matchLabels:
      app: availability
  template:
    metadata:
      labels:
        app: availability
      # Uncomment the following annotations to enable Dapr
      # annotations:
      #   dapr.io/enabled: "true"
      #   dapr.io/app-id: "availabilityapp"
      #   dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: availability
          image: ghcr.io/shubham1172/daprcon/availability:latest
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: availability
  labels:
    name: availability
spec:
  selector:
    app: availability
  type: LoadBalancer
  ports:
    - port: 8000
      name: http
      targetPort: 80
      protocol: TCP
