apiVersion: apps/v1
kind: Deployment
metadata:
  name: contosoapp
  labels:
    app: contoso
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contoso
  template:
    metadata:
      labels:
        app: contoso
    spec:
      containers:
        - name: contoso
          image: ghcr.io/shubham1172/daprcon/contoso:latest
          resources:
            limits:
              cpu: 1
              memory: 1Gi
          ports:
            - containerPort: 8080
