apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendapp
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      # Uncomment the following annotations to enable Dapr
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "frontendapp"
        dapr.io/app-port: "9000"
        dapr.io/config: "appconfig"
        dapr.io/enable-api-logging: "true"
        dapr.io/log-level: "debug"
    spec:
      containers:
        - name: frontend
          image: ghcr.io/shubham1172/daprcon/frontend:latest
          env:
            # Use these when Dapr is disabled
            # - name: WHEREBUY_AVAILABILITY_API_URL
            #   value: http://availability/check
            # - name: WHEREBUY_PRODUCT_API_URL
            #   value: http://product/get
            # Use these when Dapr is enabled
            - name: WHEREBUY_AVAILABILITY_API_URL
              value: http://localhost:3500/v1.0/invoke/availabilityapp/method/check
            - name: WHEREBUY_PRODUCT_API_URL
              value: http://localhost:3500/v1.0/invoke/productapp/method/get
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
