apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapp
  labels:
    app: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
      # Uncomment the following annotations to enable Dapr
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "productapp"
        dapr.io/app-port: "8001"
        dapr.io/config: "appconfig"
        dapr.io/enable-api-logging: "true"
        dapr.io/log-level: "debug"
    spec:
      containers:
        - name: product
          image: ghcr.io/shubham1172/daprcon/product:latest
          resources:
            limits:
              cpu: 1
              memory: 1Gi
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    name: product
spec:
  selector:
    app: product
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
